-- Read-only schema snapshot of the public schema: types, sequences, tables,
-- constraints, indexes, functions, views, triggers, and RLS policies — in an
-- order that replays into an empty Supabase project. Run in the Supabase SQL
-- editor; it returns one row with one text column (`ddl`). Copy that value
-- into supabase/schema-snapshot.sql. Changes nothing.
with
enums as (
  select string_agg(format('create type public.%I as enum (%s);', t.typname,
           (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) from pg_enum e where e.enumtypid = t.oid)),
         E'\n' order by t.typname) as s
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace and n.nspname = 'public'
  where t.typtype = 'e'
),
seqs as (
  select string_agg(format('create sequence if not exists public.%I;', c.relname), E'\n' order by c.relname) as s
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where c.relkind = 'S'
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'i') -- skip identity-owned
),
cols as (
  select c.relname as tbl,
         string_agg(
           format('  %I %s%s%s', a.attname,
                  format_type(a.atttypid, a.atttypmod),
                  case when a.attnotnull then ' not null' else '' end,
                  case
                    when a.attidentity = 'a' then ' generated always as identity'
                    when a.attidentity = 'd' then ' generated by default as identity'
                    when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                    else coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '')
                  end),
           E',\n' order by a.attnum) as body
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where c.relkind = 'r'
  group by c.relname
),
tables as (
  select string_agg(format(E'create table if not exists public.%I (\n%s\n);', tbl, body), E'\n\n' order by tbl) as s from cols
),
-- Primary keys/uniques/checks first, foreign keys last, so it replays in order.
cons as (
  select string_agg(format('alter table public.%I add constraint %I %s;', c.relname, k.conname, pg_get_constraintdef(k.oid)),
                    E'\n' order by (k.contype = 'f'), c.relname, k.conname) as s
  from pg_constraint k
  join pg_class c on c.oid = k.conrelid
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where k.contype in ('p', 'u', 'c', 'f', 'x')
),
idx as (
  select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by c.relname) as s
  from pg_index i
  join pg_class c on c.oid = i.indrelid
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where not exists (select 1 from pg_constraint k where k.conindid = i.indexrelid)
),
views as (
  select string_agg(format(E'create or replace view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true)), E'\n\n') as s
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where c.relkind = 'v'
),
funcs as (
  select string_agg(pg_get_functiondef(p.oid) || ';', E'\n\n' order by p.proname) as s
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace and n.nspname = 'public'
  where p.prokind = 'f'
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
),
trigs as (
  select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n' order by c.relname) as s
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where not t.tgisinternal
),
rls as (
  select string_agg(format('alter table public.%I enable row level security;', c.relname), E'\n' order by c.relname) as s
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where c.relkind = 'r' and c.relrowsecurity
),
pols as (
  select string_agg(format('create policy %I on public.%I as %s for %s to %s%s%s;',
           policyname, tablename, permissive, cmd, array_to_string(roles, ', '),
           coalesce(' using (' || qual || ')', ''),
           coalesce(' with check (' || with_check || ')', '')),
         E'\n' order by tablename, policyname) as s
  from pg_policies where schemaname = 'public'
),
storage_pols as (
  select string_agg(format('-- storage.%I policy %I: %s to %s using (%s) with check (%s)',
           tablename, policyname, cmd, array_to_string(roles, ', '), qual, with_check),
         E'\n' order by tablename, policyname) as s
  from pg_policies where schemaname = 'storage'
),
exts as (
  select string_agg(format('-- extension %s %s (schema %s)', e.extname, e.extversion, n.nspname), E'\n' order by e.extname) as s
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
)
select concat_ws(E'\n\n',
  '-- ===== extensions (reference only) =====', (select s from exts),
  'set check_function_bodies = off;',
  '-- ===== types =====', (select s from enums),
  '-- ===== sequences =====', (select s from seqs),
  '-- ===== functions =====', (select s from funcs),
  '-- ===== tables =====', (select s from tables),
  '-- ===== constraints =====', (select s from cons),
  '-- ===== indexes =====', (select s from idx),
  '-- ===== views =====', (select s from views),
  '-- ===== triggers =====', (select s from trigs),
  '-- ===== rls =====', (select s from rls),
  '-- ===== policies =====', (select s from pols),
  '-- ===== storage policies (reference only) =====', (select s from storage_pols)
) as ddl;
